# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_v3.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CarpalTunnelUNetPrediction(object):
    def setupUi(self, CarpalTunnelUNetPrediction):
        CarpalTunnelUNetPrediction.setObjectName("CarpalTunnelUNetPrediction")
        CarpalTunnelUNetPrediction.resize(1113, 799)
        CarpalTunnelUNetPrediction.setMinimumSize(QtCore.QSize(1113, 799))
        CarpalTunnelUNetPrediction.setMaximumSize(QtCore.QSize(1113, 799))
        self.centralwidget = QtWidgets.QWidget(CarpalTunnelUNetPrediction)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem)
        self.lb_pid = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_pid.setFont(font)
        self.lb_pid.setObjectName("lb_pid")
        self.horizontalLayout_24.addWidget(self.lb_pid)
        self.cBox_pid = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_pid.setMinimumSize(QtCore.QSize(128, 0))
        self.cBox_pid.setMaximumSize(QtCore.QSize(128, 16777215))
        font = QtGui.QFont()
        font.setFamily("Goldman Sans Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cBox_pid.setFont(font)
        self.cBox_pid.setObjectName("cBox_pid")
        self.cBox_pid.addItem("")
        self.cBox_pid.addItem("")
        self.cBox_pid.addItem("")
        self.cBox_pid.addItem("")
        self.cBox_pid.addItem("")
        self.cBox_pid.addItem("")
        self.cBox_pid.addItem("")
        self.cBox_pid.addItem("")
        self.cBox_pid.addItem("")
        self.cBox_pid.addItem("")
        self.horizontalLayout_24.addWidget(self.cBox_pid)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_24.addLayout(self.horizontalLayout)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.b_pidConfirm = QtWidgets.QPushButton(self.centralwidget)
        self.b_pidConfirm.setMinimumSize(QtCore.QSize(128, 0))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.b_pidConfirm.setFont(font)
        self.b_pidConfirm.setObjectName("b_pidConfirm")
        self.horizontalLayout_25.addWidget(self.b_pidConfirm)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_25)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.lb_img_t1 = QtWidgets.QLabel(self.centralwidget)
        self.lb_img_t1.setMinimumSize(QtCore.QSize(224, 224))
        self.lb_img_t1.setMaximumSize(QtCore.QSize(224, 224))
        self.lb_img_t1.setText("")
        self.lb_img_t1.setObjectName("lb_img_t1")
        self.verticalLayout.addWidget(self.lb_img_t1)
        self.lb_t1_image = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_t1_image.setFont(font)
        self.lb_t1_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_t1_image.setObjectName("lb_t1_image")
        self.verticalLayout.addWidget(self.lb_t1_image)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.lb_img_t2 = QtWidgets.QLabel(self.centralwidget)
        self.lb_img_t2.setMinimumSize(QtCore.QSize(224, 224))
        self.lb_img_t2.setMaximumSize(QtCore.QSize(224, 224))
        self.lb_img_t2.setText("")
        self.lb_img_t2.setObjectName("lb_img_t2")
        self.verticalLayout.addWidget(self.lb_img_t2)
        self.lb_t2_image = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_t2_image.setFont(font)
        self.lb_t2_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_t2_image.setObjectName("lb_t2_image")
        self.verticalLayout.addWidget(self.lb_t2_image)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.lb_img_mn_gt = QtWidgets.QLabel(self.centralwidget)
        self.lb_img_mn_gt.setMinimumSize(QtCore.QSize(160, 160))
        self.lb_img_mn_gt.setMaximumSize(QtCore.QSize(160, 160))
        self.lb_img_mn_gt.setText("")
        self.lb_img_mn_gt.setObjectName("lb_img_mn_gt")
        self.verticalLayout_5.addWidget(self.lb_img_mn_gt)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.lb_gt_Image = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_gt_Image.setFont(font)
        self.lb_gt_Image.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_gt_Image.setObjectName("lb_gt_Image")
        self.verticalLayout_5.addWidget(self.lb_gt_Image)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem12)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem13)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem14)
        self.lb_img_ft_gt = QtWidgets.QLabel(self.centralwidget)
        self.lb_img_ft_gt.setMinimumSize(QtCore.QSize(160, 160))
        self.lb_img_ft_gt.setMaximumSize(QtCore.QSize(160, 160))
        self.lb_img_ft_gt.setText("")
        self.lb_img_ft_gt.setObjectName("lb_img_ft_gt")
        self.verticalLayout_4.addWidget(self.lb_img_ft_gt)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem15)
        self.lb_gt_Image_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_gt_Image_2.setFont(font)
        self.lb_gt_Image_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_gt_Image_2.setObjectName("lb_gt_Image_2")
        self.verticalLayout_4.addWidget(self.lb_gt_Image_2)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem16)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem17)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem18)
        self.lb_img_ct_gt = QtWidgets.QLabel(self.centralwidget)
        self.lb_img_ct_gt.setMinimumSize(QtCore.QSize(160, 160))
        self.lb_img_ct_gt.setMaximumSize(QtCore.QSize(160, 160))
        self.lb_img_ct_gt.setText("")
        self.lb_img_ct_gt.setObjectName("lb_img_ct_gt")
        self.verticalLayout_3.addWidget(self.lb_img_ct_gt)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem19)
        self.lb_gt_Image_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_gt_Image_3.setFont(font)
        self.lb_gt_Image_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_gt_Image_3.setObjectName("lb_gt_Image_3")
        self.verticalLayout_3.addWidget(self.lb_gt_Image_3)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem20)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem21)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem22)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem23)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem24)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem25)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem26)
        self.lb_img_mn_pred = QtWidgets.QLabel(self.centralwidget)
        self.lb_img_mn_pred.setMinimumSize(QtCore.QSize(160, 160))
        self.lb_img_mn_pred.setMaximumSize(QtCore.QSize(160, 160))
        self.lb_img_mn_pred.setText("")
        self.lb_img_mn_pred.setObjectName("lb_img_mn_pred")
        self.verticalLayout_7.addWidget(self.lb_img_mn_pred)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem27)
        self.lb_pred_Image = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_pred_Image.setFont(font)
        self.lb_pred_Image.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_pred_Image.setObjectName("lb_pred_Image")
        self.verticalLayout_7.addWidget(self.lb_pred_Image)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem28)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem29)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem30)
        self.lb_img_ft_pred = QtWidgets.QLabel(self.centralwidget)
        self.lb_img_ft_pred.setMinimumSize(QtCore.QSize(160, 160))
        self.lb_img_ft_pred.setMaximumSize(QtCore.QSize(160, 160))
        self.lb_img_ft_pred.setText("")
        self.lb_img_ft_pred.setObjectName("lb_img_ft_pred")
        self.verticalLayout_8.addWidget(self.lb_img_ft_pred)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem31)
        self.lb_pred_Image_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_pred_Image_2.setFont(font)
        self.lb_pred_Image_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_pred_Image_2.setObjectName("lb_pred_Image_2")
        self.verticalLayout_8.addWidget(self.lb_pred_Image_2)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem32)
        self.verticalLayout_6.addLayout(self.verticalLayout_8)
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem33)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem34)
        self.lb_img_ct_pred = QtWidgets.QLabel(self.centralwidget)
        self.lb_img_ct_pred.setMinimumSize(QtCore.QSize(160, 160))
        self.lb_img_ct_pred.setMaximumSize(QtCore.QSize(160, 160))
        self.lb_img_ct_pred.setText("")
        self.lb_img_ct_pred.setObjectName("lb_img_ct_pred")
        self.verticalLayout_9.addWidget(self.lb_img_ct_pred)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem35)
        self.lb_pred_Image_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_pred_Image_3.setFont(font)
        self.lb_pred_Image_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_pred_Image_3.setObjectName("lb_pred_Image_3")
        self.verticalLayout_9.addWidget(self.lb_pred_Image_3)
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem36)
        self.verticalLayout_6.addLayout(self.verticalLayout_9)
        spacerItem37 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem37)
        spacerItem38 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem38)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_2)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem39)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem40 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem40)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lb_img_result = QtWidgets.QLabel(self.centralwidget)
        self.lb_img_result.setMinimumSize(QtCore.QSize(320, 320))
        self.lb_img_result.setMaximumSize(QtCore.QSize(320, 320))
        self.lb_img_result.setText("")
        self.lb_img_result.setObjectName("lb_img_result")
        self.verticalLayout_10.addWidget(self.lb_img_result)
        self.lb_result_image = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_result_image.setFont(font)
        self.lb_result_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_result_image.setObjectName("lb_result_image")
        self.verticalLayout_10.addWidget(self.lb_result_image)
        self.verticalLayout_14.addLayout(self.verticalLayout_10)
        spacerItem41 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem41)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gBox_seq = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.gBox_seq.setFont(font)
        self.gBox_seq.setObjectName("gBox_seq")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.gBox_seq)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lb_seq_mn_lb = QtWidgets.QLabel(self.gBox_seq)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_seq_mn_lb.setFont(font)
        self.lb_seq_mn_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_seq_mn_lb.setObjectName("lb_seq_mn_lb")
        self.horizontalLayout_6.addWidget(self.lb_seq_mn_lb)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem42)
        self.lb_seq_mn_val = QtWidgets.QLabel(self.gBox_seq)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_seq_mn_val.setFont(font)
        self.lb_seq_mn_val.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_seq_mn_val.setObjectName("lb_seq_mn_val")
        self.horizontalLayout_6.addWidget(self.lb_seq_mn_val)
        self.verticalLayout_17.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lb_seq_ft_lb = QtWidgets.QLabel(self.gBox_seq)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_seq_ft_lb.setFont(font)
        self.lb_seq_ft_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_seq_ft_lb.setObjectName("lb_seq_ft_lb")
        self.horizontalLayout_5.addWidget(self.lb_seq_ft_lb)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem43)
        self.lb_seq_ft_val = QtWidgets.QLabel(self.gBox_seq)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_seq_ft_val.setFont(font)
        self.lb_seq_ft_val.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_seq_ft_val.setObjectName("lb_seq_ft_val")
        self.horizontalLayout_5.addWidget(self.lb_seq_ft_val)
        self.verticalLayout_17.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_seq_ct_lb = QtWidgets.QLabel(self.gBox_seq)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_seq_ct_lb.setFont(font)
        self.lb_seq_ct_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_seq_ct_lb.setObjectName("lb_seq_ct_lb")
        self.horizontalLayout_4.addWidget(self.lb_seq_ct_lb)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem44)
        self.lb_seq_ct_val = QtWidgets.QLabel(self.gBox_seq)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_seq_ct_val.setFont(font)
        self.lb_seq_ct_val.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_seq_ct_val.setObjectName("lb_seq_ct_val")
        self.horizontalLayout_4.addWidget(self.lb_seq_ct_val)
        self.verticalLayout_17.addLayout(self.horizontalLayout_4)
        self.verticalLayout_13.addWidget(self.gBox_seq)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.gBox_single = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.gBox_single.setFont(font)
        self.gBox_single.setObjectName("gBox_single")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.gBox_single)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lb_single_mn_lb = QtWidgets.QLabel(self.gBox_single)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_single_mn_lb.setFont(font)
        self.lb_single_mn_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_single_mn_lb.setObjectName("lb_single_mn_lb")
        self.horizontalLayout_7.addWidget(self.lb_single_mn_lb)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem45)
        self.lb_single_mn_val = QtWidgets.QLabel(self.gBox_single)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_single_mn_val.setFont(font)
        self.lb_single_mn_val.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_single_mn_val.setObjectName("lb_single_mn_val")
        self.horizontalLayout_7.addWidget(self.lb_single_mn_val)
        self.verticalLayout_19.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lb_single_ft_lb = QtWidgets.QLabel(self.gBox_single)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_single_ft_lb.setFont(font)
        self.lb_single_ft_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_single_ft_lb.setObjectName("lb_single_ft_lb")
        self.horizontalLayout_8.addWidget(self.lb_single_ft_lb)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem46)
        self.lb_single_ft_val = QtWidgets.QLabel(self.gBox_single)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_single_ft_val.setFont(font)
        self.lb_single_ft_val.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_single_ft_val.setObjectName("lb_single_ft_val")
        self.horizontalLayout_8.addWidget(self.lb_single_ft_val)
        self.verticalLayout_19.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lb_single_ct_lb = QtWidgets.QLabel(self.gBox_single)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_single_ct_lb.setFont(font)
        self.lb_single_ct_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_single_ct_lb.setObjectName("lb_single_ct_lb")
        self.horizontalLayout_9.addWidget(self.lb_single_ct_lb)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem47)
        self.lb_single_ct_val = QtWidgets.QLabel(self.gBox_single)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_single_ct_val.setFont(font)
        self.lb_single_ct_val.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_single_ct_val.setObjectName("lb_single_ct_val")
        self.horizontalLayout_9.addWidget(self.lb_single_ct_val)
        self.verticalLayout_19.addLayout(self.horizontalLayout_9)
        self.verticalLayout_15.addWidget(self.gBox_single)
        self.verticalLayout_14.addLayout(self.verticalLayout_15)
        spacerItem48 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem48)
        self.horizontalLayout_10.addLayout(self.verticalLayout_14)
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem49)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.slider_patient_id = QtWidgets.QSlider(self.centralwidget)
        self.slider_patient_id.setMaximum(9)
        self.slider_patient_id.setOrientation(QtCore.Qt.Horizontal)
        self.slider_patient_id.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_patient_id.setTickInterval(1)
        self.slider_patient_id.setObjectName("slider_patient_id")
        self.horizontalLayout_3.addWidget(self.slider_patient_id)
        self.lb_slider = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_slider.setFont(font)
        self.lb_slider.setObjectName("lb_slider")
        self.horizontalLayout_3.addWidget(self.lb_slider)
        self.b_sliderSelect = QtWidgets.QPushButton(self.centralwidget)
        self.b_sliderSelect.setMinimumSize(QtCore.QSize(96, 0))
        self.b_sliderSelect.setMaximumSize(QtCore.QSize(96, 16777215))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.b_sliderSelect.setFont(font)
        self.b_sliderSelect.setObjectName("b_sliderSelect")
        self.horizontalLayout_3.addWidget(self.b_sliderSelect)
        self.b_sliderNext = QtWidgets.QPushButton(self.centralwidget)
        self.b_sliderNext.setMinimumSize(QtCore.QSize(96, 0))
        self.b_sliderNext.setMaximumSize(QtCore.QSize(96, 16777215))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.b_sliderNext.setFont(font)
        self.b_sliderNext.setObjectName("b_sliderNext")
        self.horizontalLayout_3.addWidget(self.b_sliderNext)
        spacerItem50 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem50)
        self.verticalLayout_12.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        CarpalTunnelUNetPrediction.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CarpalTunnelUNetPrediction)
        self.statusbar.setObjectName("statusbar")
        CarpalTunnelUNetPrediction.setStatusBar(self.statusbar)

        self.retranslateUi(CarpalTunnelUNetPrediction)
        QtCore.QMetaObject.connectSlotsByName(CarpalTunnelUNetPrediction)

    def retranslateUi(self, CarpalTunnelUNetPrediction):
        _translate = QtCore.QCoreApplication.translate
        CarpalTunnelUNetPrediction.setWindowTitle(_translate("CarpalTunnelUNetPrediction", "UNet Prediction"))
        self.lb_pid.setText(_translate("CarpalTunnelUNetPrediction", "Patient ID : "))
        self.cBox_pid.setItemText(0, _translate("CarpalTunnelUNetPrediction", "0"))
        self.cBox_pid.setItemText(1, _translate("CarpalTunnelUNetPrediction", "1"))
        self.cBox_pid.setItemText(2, _translate("CarpalTunnelUNetPrediction", "2"))
        self.cBox_pid.setItemText(3, _translate("CarpalTunnelUNetPrediction", "3"))
        self.cBox_pid.setItemText(4, _translate("CarpalTunnelUNetPrediction", "4"))
        self.cBox_pid.setItemText(5, _translate("CarpalTunnelUNetPrediction", "5"))
        self.cBox_pid.setItemText(6, _translate("CarpalTunnelUNetPrediction", "6"))
        self.cBox_pid.setItemText(7, _translate("CarpalTunnelUNetPrediction", "7"))
        self.cBox_pid.setItemText(8, _translate("CarpalTunnelUNetPrediction", "8"))
        self.cBox_pid.setItemText(9, _translate("CarpalTunnelUNetPrediction", "9"))
        self.b_pidConfirm.setText(_translate("CarpalTunnelUNetPrediction", "Confirm"))
        self.lb_t1_image.setText(_translate("CarpalTunnelUNetPrediction", "T1 Images"))
        self.lb_t2_image.setText(_translate("CarpalTunnelUNetPrediction", "T2 Images"))
        self.lb_gt_Image.setText(_translate("CarpalTunnelUNetPrediction", "MN GroundTruth"))
        self.lb_gt_Image_2.setText(_translate("CarpalTunnelUNetPrediction", "FT GroundTruth"))
        self.lb_gt_Image_3.setText(_translate("CarpalTunnelUNetPrediction", "CT GroundTruth"))
        self.lb_pred_Image.setText(_translate("CarpalTunnelUNetPrediction", "MN Prediction"))
        self.lb_pred_Image_2.setText(_translate("CarpalTunnelUNetPrediction", "FT Prediction"))
        self.lb_pred_Image_3.setText(_translate("CarpalTunnelUNetPrediction", "CT Prediction"))
        self.lb_result_image.setText(_translate("CarpalTunnelUNetPrediction", "Segmented Image"))
        self.gBox_seq.setTitle(_translate("CarpalTunnelUNetPrediction", "Sequence DC (mean)"))
        self.lb_seq_mn_lb.setText(_translate("CarpalTunnelUNetPrediction", "Median Nerve : "))
        self.lb_seq_mn_val.setText(_translate("CarpalTunnelUNetPrediction", "-"))
        self.lb_seq_ft_lb.setText(_translate("CarpalTunnelUNetPrediction", "Flexor Tendons : "))
        self.lb_seq_ft_val.setText(_translate("CarpalTunnelUNetPrediction", "-"))
        self.lb_seq_ct_lb.setText(_translate("CarpalTunnelUNetPrediction", "Carpal Tunnel : "))
        self.lb_seq_ct_val.setText(_translate("CarpalTunnelUNetPrediction", "-"))
        self.gBox_single.setTitle(_translate("CarpalTunnelUNetPrediction", "Image DC"))
        self.lb_single_mn_lb.setText(_translate("CarpalTunnelUNetPrediction", "Median Nerve : "))
        self.lb_single_mn_val.setText(_translate("CarpalTunnelUNetPrediction", "-"))
        self.lb_single_ft_lb.setText(_translate("CarpalTunnelUNetPrediction", "Flexor Tendons : "))
        self.lb_single_ft_val.setText(_translate("CarpalTunnelUNetPrediction", "-"))
        self.lb_single_ct_lb.setText(_translate("CarpalTunnelUNetPrediction", "Carpal Tunnel : "))
        self.lb_single_ct_val.setText(_translate("CarpalTunnelUNetPrediction", "-"))
        self.lb_slider.setText(_translate("CarpalTunnelUNetPrediction", "-/-"))
        self.b_sliderSelect.setText(_translate("CarpalTunnelUNetPrediction", "Select"))
        self.b_sliderNext.setText(_translate("CarpalTunnelUNetPrediction", "Next"))
